version: '3'
services:
  postgres-test:
    image: postgres:11.4-alpine
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d